storage: ./storage
listen: 9900 #Any host:port configured in conf/config.yaml under listen is currently ignored when using docker.
publish:
  allow_offline: true
auth:
  htpasswd:
    file: ./htpasswd
    max_users: 4
uplinks:
  mDefault:
    url: http://localhost:9900
    max_fails: 100
  
packages:
  '@*/*':
    access: $authenticated
    publish: $authenticated
    proxy: mDefault
  '**':
    access: $authenticated
    publish: $authenticated
    proxy: mDefault
logs:
  - {type: stdout, format: pretty, level: http}